USE [master]
GO

/****** Object:  Database [db_robin]    Script Date: 11/20/2014 8:14:33 AM ******/
CREATE DATABASE [db_robin]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'db_robin', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\db_robin.mdf' , SIZE = 3136KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'db_robin_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\db_robin_log.ldf' , SIZE = 832KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [db_robin] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [db_robin].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [db_robin] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [db_robin] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [db_robin] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [db_robin] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [db_robin] SET ARITHABORT OFF 
GO

ALTER DATABASE [db_robin] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [db_robin] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [db_robin] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [db_robin] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [db_robin] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [db_robin] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [db_robin] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [db_robin] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [db_robin] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [db_robin] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [db_robin] SET  DISABLE_BROKER 
GO

ALTER DATABASE [db_robin] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [db_robin] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [db_robin] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [db_robin] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [db_robin] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [db_robin] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [db_robin] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [db_robin] SET RECOVERY FULL 
GO

ALTER DATABASE [db_robin] SET  MULTI_USER 
GO

ALTER DATABASE [db_robin] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [db_robin] SET DB_CHAINING OFF 
GO

ALTER DATABASE [db_robin] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [db_robin] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [db_robin] SET  READ_WRITE 
GO


